[package]
name = "wlog"
version = "0.1.0"
edition = "2024"

[dependencies]
ammonia = "4.1.4"
argon2 = "0.6.0"
askama = { version = "0.16.0", features = ["serde_json"] }
axum = { version = "0.8.9", features = ["multipart", "form", "query"] }
axum-extra = { version = "0.12.6", features = ["cookie-signed", "cookie-key-expansion"] }
chrono = "0.4.45"
comrak = { version = "0.54.0", default-features = false, features = ["syntect-fancy"] }
dotenvy = "0.15.7"
infer = "0.22.0"
rpassword = "7.5.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
slug = "0.1.6"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "tls-rustls-ring", "postgres", "chrono", "uuid", "migrate", "macros"] }
svg-hush = "0.9.7"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "signal", "net", "fs", "time"] }
tower-http = { version = "0.7.1", features = ["fs", "trace", "compression-gzip", "set-header", "request-id"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = "2.5.8"
uuid = { version = "1.26.0", features = ["v4", "serde"] }
